### ISSUE TITLE
Windows 11 git problem

### ISSUE THREAD

**Issue by gogo1989** [M3taKn1ght/AzTouchMQTTInterface#1]
Hello
I was not able to compile it on Windows 11.
(tinyxml2 was not able to install)
With Linux Mint it works without any Problem!

**Comment by M3taKn1ght** [comment]
Interessting, cause platformio works the Same way in Windows and Linux. I used it on Windows 10/11 and Linux (Debian). So not quiet sure where the problem is. Can you post the complete log?!

**Comment by gogo1989** [comment]
Hello
I got this message:
Library Manager: Installing git+https://github.com/leethomason/tinyxml2
UserSideException: Please install Git client from https://git-scm.com/downloads

I tried to install git and also the tinyxml2 as it was written, but i was not able to compile it

**Comment by M3taKn1ght** [comment]
Okay so there ist no Problem with my Code, this is a Problem with your os and Missing Software. In General, Install git and reboot, Sometimes Windows need a reboot to get the Environment.

**Comment by M3taKn1ght** [comment]
Maybe this helps Out:
https://community.platformio.org/t/git-library-download/17000

**Comment by gogo1989** [comment]
Hallo
Danke für Ihre Hilfe!
Jetz funktioniert es, Git war in Visual Studio nicht richtig konfiguriert.
Konnten Sie die Shutter auch schon implementieren?
